In [6]:
import pandas as pd
df = pd.read_csv('RR25_UW.csv', nrows=10)
print(df)

           Record Date   Entry Type  Booking ID Booking Location  \
0  2025-01-01 04:00:18  Transaction    77025249  Online checkout   
1  2025-01-01 04:00:18  Transaction    77025249  Online checkout   
2  2025-01-01 04:00:18   Adjustment    77025249  Online checkout   
3  2025-01-01 06:19:59  Transaction    85186557  Online checkout   
4  2025-01-01 07:06:59  Transaction    85187066  Online checkout   
5  2025-01-01 07:06:59  Transaction    85187066  Online checkout   
6  2025-01-01 07:15:06  Transaction    85187203  Online checkout   
7  2025-01-01 07:22:53  Transaction    85187358  Online checkout   
8  2025-01-01 07:22:53  Transaction    85187358  Online checkout   
9  2025-01-01 07:34:11  Transaction    85187623  Online checkout   

   Payment Device  Product Reporting Name  \
0             NaN                     NaN   
1             NaN                     NaN   
2             NaN                     NaN   
3             NaN                     NaN   
4             NaN         

In [7]:
df25.columns

Index(['Record Date', 'Entry Type', 'Booking ID', 'Booking Location',
       'Payment Device', 'Product Reporting Name', 'Product Name',
       'Ticket Reporting Name', 'Ticket Name', 'Funds Received', 'Discount',
       'Fee Revenue', 'Tax Collected', 'Tax %', 'Status', 'Transaction ID',
       'Transaction Location', 'Payment Method', 'Gateway ID', 'GL Code',
       'Ticket Quantity', 'Company Name', 'Tax On Fees', 'Deferred Rev',
       'Other Deferred Rev', 'Gift Card Def Rev', 'Acc Receivable',
       'Gross Revenue', 'Discounts Recognised', 'Tax Payable', 'Net Revenue',
       'Unit Cost', 'Product Id', 'Item Transaction Value', 'Item Quantity',
       'Redeemed Ticket Quantity', 'Expired Ticket Quantity',
       'Recognised Ticket Quantity', 'Credit Card Fee Amount',
       'Transaction Fee Amount', 'Product Booking Fee Amount',
       'Booking Modifier Amount', 'Discount Code Used', 'Expiry Date',
       'External Payments'],
      dtype='object')

In [5]:
df.columns

Index(['Record Date', 'Entry Type', 'Booking ID', 'Booking Location',
       'Payment Device', 'Product Reporting Name', 'Product Name',
       'Ticket Reporting Name', 'Ticket Name', 'Funds Received', 'Discount',
       'Fee Revenue', 'Tax Collected', 'Tax %', 'Status', 'Transaction ID',
       'Transaction Location', 'Payment Method', 'Gateway ID', 'GL Code',
       'Ticket Quantity', 'Company Name', 'Tax On Fees', 'Deferred Rev',
       'Other Deferred Rev', 'Gift Card Def Rev', 'Acc Receivable',
       'Gross Revenue', 'Discounts Recognised', 'Tax Payable', 'Net Revenue',
       'Unit Cost', 'Product Id', 'Item Transaction Value', 'Item Quantity',
       'Redeemed Ticket Quantity', 'Expired Ticket Quantity',
       'Recognised Ticket Quantity', 'Credit Card Fee Amount',
       'Transaction Fee Amount', 'Product Booking Fee Amount',
       'Booking Modifier Amount', 'Discount Code Used', 'Expiry Date',
       'External Payments'],
      dtype='object')

In [3]:
df25 = pd.read_csv('RR25_UW.csv')

/var/folders/_t/s9_cqvqj4_n614936xfgdv_00000gn/T/ipykernel_53477/1749042441.py:1: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df25 = pd.read_csv('RR25_UW.csv')


In [26]:
df25['Entry Type'].unique()

array(['Transaction', 'Adjustment', 'Recognition'], dtype=object)

In [17]:
df25['Booking Location'].unique()

array(['Online checkout', 'POS', 'Venue manager'], dtype=object)

In [27]:
df25['Payment Device'].unique()

array([nan, 'POS 4', 'Reception POS 2', 'POS 3', 'Mollis Ice Cream',
       'Reception POS 1', 'Juice Truck', 'Night Market: Roller Skate',
       'POS 5', 'Night Market POS 1', 'Night Market POS 2'], dtype=object)

In [28]:
df25['Product Reporting Name'].unique()

array([nan])

In [29]:
df25['Product Name'].unique()

array(['MINI ROVER Membership ($30 P/M, Non-Transferable)',
       'COSMOS, POWER PLAY - 2HRS (13+YRS)', 'ASTROTOT - 2HRS (1-2YRS)',
       'UNIVERSE, HEAD FOR HEIGHTS - 2HRS (5-12YRS)',
       'AREA 51 GRIP SOCKS', 'UNIVERSE, CLIMB THE WALLS - 1HR (5-12YRS)',
       'UNIVERSE, POWER PLAY - 2HRS (5-12 YRS)',
       'ADULT HELPER (HIGH ROPES)', 'MINI ROVER - 2HRS (3-4YRS)',
       'UNIVERSE, CLIMB THE WALLS - 2HRS (5-12YRS)', 'MILKY WAY PARTY',
       'Party Beverages', 'Kids Meals', 'TV Bday Message',
       'ADULT CARER COMPANION',
       'COSMOS, HEAD FOR HEIGHTS - 2HRS (13+YRS)',
       'UNIVERSE, HEAD FOR HEIGHTS - 1.5HRS (5-12YRS)',
       'MOLLIS ICE CREAM - 1 SCOOP (DAILY, 10AM - 8PM)', 'Drinks',
       'ECLIPSE PARTY', 'Upgrade My Party', 'Bouquet of Table Balloons',
       'Party Table Cloth Runners', 'Share Beverages',
       'GRAZING BOARDS TIL 13TH JULY', 'Staff Socks',
       'UNIVERSE, HEAD FOR HEIGHTS - 1HR (5-12YRS)',
       'POWER PLAY - 2HRS (18+YRS)',
       'COSMOS,

In [30]:
df25['Ticket Reporting Name'].unique()

array([nan])

In [4]:
df25['Ticket Name'].unique()

array(['Mini Rover Membership',
       '2 Hours - Weekends and Holidays (13+YRS)',
       '2 Hours - Public Holiday (1-2YRS)',
       '2 Hours - Public Holiday (5-12YRS)', 'AREA 51 GRIP SOCKS',
       '2 Hours - Weekends and Holidays (5-12YRS)',
       '1 Hour - Public Holiday (5-12YRS)', 'ADULT HELPER (HIGH ROPES)',
       '2 Hours - Public Holiday (3-4YRS)',
       'Milky Way Party (Weekends, Holidays)', 'Pop Top',
       'EVERY CHILD in the party gets Chicken Nuggets and Chips',
       'Hot Wheels', '1.5L Water', 'ADULT CARER COMPANION',
       '2 Hours - Public Holiday (13+YRS)',
       '1.5 Hours - Weekends and Holidays (5-12YRS)',
       'MOLLIS ICE CREAM - 1 SCOOP (DAILY, 10AM - 8PM)', 'Powerade Red',
       'Mount Franklin Water', 'Iced Tea Lemon',
       'Deluxe Eclipse (Weekends, Holidays) + $50 UPGRADE FEE',
       "Gabby's Dollhouse", 'Request to Upgrade for an ADDITIONAL $50',
       '1 x Bouquet (7pcs)', 'Purple', '600ml Water', 'Coke 2 LITRES',
       'Rasberry 1.1 LITRE

In [5]:
df25['Ticket Name'].nunique()

755

In [32]:
df25['Funds Received'].unique()

array([ 30.  ,   0.  ,  18.62, ..., 249.08,  14.82,  55.57],
      shape=(11656,))

In [33]:
df25['Discount'].unique()

array([ 0.0000e+00,  1.3500e+00,  1.0500e+00,  1.2000e+00,  6.9000e+01,
        4.2000e+00,  2.1900e+00,  1.8000e+02,  6.0000e+01, -8.0000e+01,
        4.9000e-01,  1.0200e+02,  5.1000e+01,  3.0000e+01,  7.0000e-01,
        6.0000e-01,  5.0000e-01,  7.5000e+00,  4.5000e+01,  1.0000e+00,
        2.5500e+00,  1.6500e+00,  2.2500e+00,  1.1000e+00,  2.8000e+01,
        4.0000e+01,  1.4000e+00,  9.0000e+01,  2.7000e+00,  1.5000e+01,
        9.0000e-01,  7.7000e-01,  3.6000e+00,  2.5800e+00,  7.5000e-01,
        2.5900e+00,  1.2000e+02,  1.5000e+00,  1.8000e+00,  1.2500e+00,
        8.6000e-01,  8.0000e-01,  6.9000e-01,  3.9000e+00,  1.8000e+01,
        2.0000e+01,  1.5680e+01,  8.4000e+00,  3.9200e+00,  5.6000e+01,
        2.1000e+00,  1.5000e+02,  1.3700e+00,  3.9000e-01,  3.3000e+02,
        1.0500e+02,  4.5000e+00,  3.0000e+00,  2.1100e+00,  2.0000e+00,
        1.4000e+01,  6.0000e+00,  5.6000e+00,  1.2000e+01,  4.2000e+01,
        2.4000e+01,  8.0000e+00, -8.0000e+00,  9.4000e-01,  2.28

In [34]:
df25['Fee Revenue'].unique()

array([ 0.  ,  1.37,  3.18, ..., 16.18,  9.96,  6.08], shape=(1645,))

In [35]:
df25['Tax Collected'].unique()

array([ 2.73,  0.  ,  1.57, ..., 36.71, 38.37, 24.36], shape=(3008,))

In [36]:
df25['Tax %'].unique()

array([10.,  0.])

In [37]:
df25['Status'].unique()

array(['Fully Paid', 'Partially Paid', 'Cancelled', 'Pending',
       'Complimentary'], dtype=object)

In [38]:
df25['Transaction Location'].unique()

array(['Recurring billing', 'Online checkout', 'POS', 'Venue manager'],
      dtype=object)

In [39]:
df25['Payment Method'].unique()

array(['Cards', nan, 'Cash', 'Gift card', 'Other', 'Bank transfer',
       'Eftpos'], dtype=object)

In [40]:
df25['Gateway ID'].unique()

array(['RGRD64KLNHCZ6RF3', nan, 'SSC9R96PH27WGMK9', ...,
       'CJW5XG2L53KTPCH4', 'NL2GBW3QXVLQ2CM4', 'R3FBSNLFHZWW2WF9'],
      shape=(114282,), dtype=object)

In [41]:
df25['GL Code'].unique()

array(['003', '001-4', '001-1', '001-3', '002-1', '002-3', '001-2',
       '005-8', '005 - 5', '1234', '016', '002-7', '011', '008-10',
       '005 - 4', '001-5', '01-6', '007', '015', '012', '020', '014',
       '202-555', '002-8', '019', '002-6', '010', '008-14', '008-11',
       '017', '005-9', '008', '008-12', '013', '005 - 7', '009', '008-13',
       'STAGE', '001-052', nan], dtype=object)

In [42]:
df25['Ticket Quantity'].unique()

array([   0,    1,    3,    2,    4,   11,    6,   10,    5,   -1,   -4,
         -2,   -3,    7,   16,   12,    9,   29,  -28,   14,    8,   25,
         -8,   -5,   20,   15,  -10,  -15,  -20,   13,  -13,  -18,   -6,
         30,  -30,   -7,  -17,  -63,  -60,  -29,  -38,   24,  -11,   51,
         80,   32,   17,   18,   50,   60,  -50,  -12,  -32,  -80,  -23,
         23,  -16, -220,   65,  220,   36,   45,  167,  -36,  -65,  -25,
         40,  -40,   75,  -45, -167,  150,  120,  132,   34,  153,  -77,
        -76,   -9,   55,  -55,   90, -120,  -14,  -26, -141,  -70,  -71,
       -132,  141,   70,   71,   86,   56,   27,  -86,   33,   44,   19,
         21,  -21,  -31,   22,   49,   63, -125,  125,  -90,   28,   31,
         61,  200,   85,  100, -100,   46,  -22,  -61,   76,   77,  180,
         48,  160,   68, -200,   26])

In [43]:
df25['Company Name'].unique()

array([nan, 'Uniting Care', 'Mount Cotton Physical Culture'], dtype=object)

In [44]:
df25['Tax On Fees'].unique()

array([0.])

In [45]:
df25['Deferred Rev'].unique()

array([  29.58,    0.  ,  -29.58, ..., -384.  ,  267.93,   63.79],
      shape=(9390,))

In [46]:
df25['Other Deferred Rev'].unique()

array([0.])

In [47]:
df25['Gift Card Def Rev'].unique()

array([ 0.0000e+00, -4.6000e+01,  3.4500e+01, -3.5000e+01, -2.2500e+01,
       -2.5000e+01, -2.8500e+01, -6.0000e+01, -6.7000e+01, -3.0000e+01,
       -4.0000e+01,  4.0000e+01, -5.8000e+01, -5.7000e+01, -4.3000e+01,
       -1.8000e+01,  6.7000e+01, -1.0000e+02, -3.3500e+01, -4.5000e+01,
       -1.0500e+01,  3.0000e+01, -5.0000e+01,  2.0000e+01,  2.8000e+01,
        1.0000e+02, -8.7000e+01, -2.7500e+01, -2.0000e+01,  2.5000e+01,
       -2.6500e+01, -2.7000e+01, -8.0000e+00, -7.7000e+01, -3.9500e+01,
       -9.3500e+01,  8.0000e+01,  6.0000e+01, -1.0050e+02,  1.5000e+02,
       -3.5000e+00, -2.8000e+01, -7.5000e+00,  4.5000e+01,  1.4000e+01,
       -9.5000e+01, -7.1000e+01, -2.3500e+01, -3.2500e+01, -4.0000e+00,
       -3.0000e+00, -4.8000e+01, -8.4500e+01, -3.6000e+01, -2.4000e+01,
       -3.7000e+01, -1.3000e+01,  5.6000e+01,  3.6000e+01,  1.5000e+01,
        8.7000e+01, -5.2195e+02,  4.7000e+01, -8.5000e+00,  9.5500e+01,
       -7.3000e+01, -1.5000e+02, -9.0000e+01, -1.3050e+02,  7.60

In [48]:
df25['Acc Receivable'].unique()

array([  0.  ,   2.21,   0.73, ...,  13.13,  14.59, -14.59], shape=(3310,))

In [49]:
df25['Gross Revenue'].unique()

array([  0.  ,  30.  ,   2.45, ...,  27.37,  10.56, 384.  ], shape=(1501,))

In [50]:
df25['Discounts Recognised'].unique()

array([ 0.0000e+00,  1.0500e+00,  1.3500e+00,  1.2000e+00,  1.7300e+00,
        4.6000e+01,  3.4500e+01,  4.2000e+00,  2.1900e+00,  3.0000e+01,
        6.0000e+01,  4.9000e-01,  6.0000e-01,  7.0000e-01,  5.0000e-01,
        1.0000e+00,  1.6500e+00,  2.2500e+00,  2.5500e+00,  1.1000e+00,
        2.8000e+01,  1.4000e+00,  9.0000e+01,  9.0000e-01,  1.4000e+01,
        1.0000e+01,  7.7000e-01,  1.5000e+01,  3.6000e+00,  7.5000e-01,
        2.5800e+00,  2.5900e+00,  2.7000e+00,  4.0000e+01,  1.2500e+00,
        1.8000e+00,  8.6000e-01,  1.5000e+00, -1.4000e+00,  8.0000e-01,
        6.9000e-01,  3.9000e+00,  3.9200e+00,  8.4000e+00,  1.5680e+01,
        5.6000e+01,  1.8000e+01,  2.0000e+01,  2.1000e+00, -1.5000e+01,
        1.3700e+00,  3.9000e-01,  7.5000e+00,  2.1100e+00,  6.0000e+00,
        5.6000e+00,  3.0000e+00, -6.0000e+00,  9.4000e-01,  8.0000e+00,
        2.2800e+00,  2.0000e+00, -3.0000e+01,  5.4000e+00,  1.0000e+02,
        1.2200e+00,  1.4600e+00,  9.5000e-01,  1.1200e+00,  9.90

In [52]:
df25['Tax Payable'].unique()

array([ 0.0000e+00,  2.7300e+00,  2.2000e-01,  2.9000e-01,  2.5000e-01,
        4.1800e+00,  2.9100e+00,  2.0900e+00,  3.2000e-01,  3.1400e+00,
        9.1000e-01,  2.9800e+00,  1.5700e+00,  1.5900e+00,  9.4100e+00,
        9.5000e-01,  1.9100e+00,  1.5680e+01,  1.2700e+00,  1.6400e+00,
        6.2700e+00, -2.9100e+00,  1.2550e+01, -1.2550e+01,  8.3600e+00,
       -6.2700e+00,  6.4000e-01,  5.5000e-01,  4.3600e+00,  3.9000e-01,
       -3.1400e+00,  1.6730e+01, -4.1800e+00,  3.2700e+00,  6.8000e-01,
        8.2000e-01,  5.0000e-01,  3.6000e-01,  2.3000e-01,  4.1000e-01,
        3.8200e+00,  1.2200e+00,  6.6000e-01,  6.0000e-01,  2.3500e+00,
        7.8000e-01,  7.7000e-01,  1.8200e+00,  5.9000e-01, -1.5700e+00,
        2.2300e+00, -1.2700e+00,  4.5000e-01, -4.5000e-01,  3.7000e-01,
        1.0300e+00,  5.8200e+00,  3.2730e+01,  2.4000e+00,  2.7000e-01,
       -5.8200e+00,  8.0000e-01,  1.2300e+00,  5.3000e-01,  1.3600e+00,
        7.2100e+00,  7.3000e-01,  9.0000e-02,  4.0000e-01,  1.45

In [53]:
df25['Net Revenue'].unique()

array([   0.  ,   27.27,    2.23, ..., -203.64,   24.88,  349.09],
      shape=(1480,))

In [54]:
df25['Unit Cost'].unique()

array([2.400e+02, 4.000e+01, 1.725e+01, 3.450e+01, 3.500e+00, 3.000e+01,
       2.300e+01, 1.000e+01, 3.200e+01, 4.600e+01, 0.000e+00, 2.500e+01,
       5.000e+00, 4.500e+00, 4.000e+00, 6.000e+00, 9.000e+00, 6.500e+01,
       1.800e+01, 3.600e+02, 2.100e+01, 2.000e+01, 5.000e+01, 2.000e+00,
       8.000e+00, 4.270e+00, 3.000e+00, 7.500e+00, 5.500e+00, 2.500e+00,
       8.540e+00, 1.295e+01, 6.580e+00, 7.210e+00, 1.337e+01, 3.570e+00,
       8.470e+00, 3.990e+00, 3.500e+01, 6.000e+01, 4.060e+00, 1.134e+01,
       1.000e+00, 1.500e+01, 2.645e+01, 8.820e+00, 5.880e+00, 4.410e+00,
       2.730e+00, 9.500e+00, 6.090e+00, 5.800e+00, 1.232e+01, 5.040e+00,
       8.750e+00, 1.141e+01, 3.710e+00, 2.352e+01, 3.800e+00, 9.800e+00,
       9.450e+00, 7.280e+00, 6.800e+00, 4.100e+00, 6.500e+00, 4.200e+00,
       1.400e+00, 7.300e+00, 7.800e+00, 1.095e+01, 5.600e+00, 4.990e+00,
       9.240e+00, 1.260e+00, 7.200e+00, 1.995e+01, 5.900e+00, 8.950e+00,
       5.950e+00, 1.197e+01, 2.800e+01, 2.233e+01, 

In [55]:
df25['Product Id'].unique()

array([622470, 628934, 628051, 632535, 654213, 632534, 632523, 782341,
       619539, 628063, 632527, 805899, 766141, 711147, 744837, 772004,
       711145, 627096, 628077, 767285, 629626, 591032, 591039, 591066,
       632526, 793783, 772003, 793778, 685003, 716244, 712071, 665670,
       665673, 665672, 744693, 810939, 632531, 656204, 628075, 665254,
       627309, 679287, 619328, 628935, 629049, 628062, 632522, 666264,
       706358, 655209, 653143, 626288, 573623, 628074, 628806, 616492,
       616491, 628807, 823475, 767211, 591034, 724898, 629014, 642579,
       706361, 618117, 618981, 581323, 591052, 818589, 591038, 591051,
       591043, 628076, 627308, 736501, 629013, 832400, 591047, 738985,
       618115, 670210, 762695, 762696, 658234, 741626, 787400, 658682,
       619334, 617941, 617917, 628931, 616493, 591037, 656498, 793780,
       771998, 793807, 712066, 623453, 637330, 744836, 771995, 689469,
       771854, 618116, 748319, 655208, 591045, 771036, 655206, 619325,
      

In [56]:
df25['Item Transaction Value'].unique()

array([ 30.  ,   0.  ,  18.62, ..., 249.08,  14.82,  55.57], shape=(8084,))

In [57]:
df25['Item Quantity'].unique()

array([   0,    1,    3,    2,    4,   11,    6,   10,    5,   -1,   -4,
         -2,   -3,    7,   16,   12,    9,   29,  -28,   14,    8,   25,
         -8,   -5,   20,   15,  -10,  -15,  -20,   13,  -13,  -18,   -6,
         30,  -30,   -7,  -17,  -63,  -60,  -29,  -38,   24,  -11,   51,
         80,   32,   17,   18,   50,   60,  -50,  -12,  -32,  -80,  -23,
         23,  -16, -220,   65,  220,   36,   45,  167,  -36,  -65,  -25,
         40,  -40,   75,  -45, -167,  150,  120,  132,   34,  153,  -77,
        -76,   -9,   55,  -55,   90, -120,  -14,  -26, -141,  -70,  -71,
       -132,  141,   70,   71,   86,   56,   27,  -86,   33,   44,   19,
         21,  -21,  -31,   22,   49,   63, -125,  125,  -90,   28,   31,
         61,  200,   85,  100, -100,   46,  -22,  -61,   76,   77,  180,
         48,  160,   68, -200,   26])

In [58]:
df25['Redeemed Ticket Quantity'].unique()

array([  0,   1,   5,   3,  -1,   6,   4,   2,  -3,  -2,   7,  -4,   8,
       -13,  14,  -5,  -7,  -6,  -8,  -9, -11,   9, -10,  11,  12,  10,
        81,  64,  44,  16,  20,  50,  15,  13,  17])

In [59]:
df25['Expired Ticket Quantity'].unique()

array([  0,   2,   1,  -1,   3,   4,   7,  -2,  15,   8,   5,  10,   6,
        13,  11,  12,  -3,  -4,  14,  16,  29,   9, -13,  -6,  50,  20,
        22, -11,  45,  72, 112, 100,  77, -20,  91,  25,  71,  18,  17,
        60,  40,  35,  53,  48,  41,  66,  88,  80,  76, 135,  67,  26,
        28,  34, -10, -14,  59,  -5, 167, 106,  24,  27,  21,  75,  55,
       125,  43,  90, 120,  39,  70,  32,  44,  84, 105, -12,  30,  -8,
        42, -16, 154,  65,  54,  56,  -7,  37])

In [60]:
df25['Recognised Ticket Quantity'].unique()

array([  0,   1,   5,   3,  -1,   6,   4,   2,  -3,  -2,   7,  -4,  15,
         8,  10,  13,  11,  12,  14,  16,  29,   9, -13,  50,  20,  -5,
        -7,  -6,  -8,  -9, -11,  22,  45, -10,  72, 112,  81, 100,  77,
        64, -20,  91,  25,  71,  18,  17,  44,  60,  40,  35,  53,  48,
        41,  66,  88,  80,  76, 135,  67,  26,  28,  34, -14,  59, 167,
       106,  24,  27,  21,  75,  55, 125,  43,  90, 120,  39,  70,  32,
        84, 105, -12,  30,  42, -16, 154,  65,  54,  56,  37])

In [61]:
df25['Credit Card Fee Amount'].unique()

array([0.])

In [62]:
df25['Transaction Fee Amount'].unique()

array([0.])

In [63]:
df25.columns

Index(['Record Date', 'Entry Type', 'Booking ID', 'Booking Location',
       'Payment Device', 'Product Reporting Name', 'Product Name',
       'Ticket Reporting Name', 'Ticket Name', 'Funds Received', 'Discount',
       'Fee Revenue', 'Tax Collected', 'Tax %', 'Status', 'Transaction ID',
       'Transaction Location', 'Payment Method', 'Gateway ID', 'GL Code',
       'Ticket Quantity', 'Company Name', 'Tax On Fees', 'Deferred Rev',
       'Other Deferred Rev', 'Gift Card Def Rev', 'Acc Receivable',
       'Gross Revenue', 'Discounts Recognised', 'Tax Payable', 'Net Revenue',
       'Unit Cost', 'Product Id', 'Item Transaction Value', 'Item Quantity',
       'Redeemed Ticket Quantity', 'Expired Ticket Quantity',
       'Recognised Ticket Quantity', 'Credit Card Fee Amount',
       'Transaction Fee Amount', 'Product Booking Fee Amount',
       'Booking Modifier Amount', 'Discount Code Used', 'Expiry Date',
       'External Payments'],
      dtype='object')

In [64]:
df25['Product Booking Fee Amount'].unique()

array([0.])

In [65]:
df25['Booking Modifier Amount'].unique()

array([0.])

In [66]:
df25['Discount Code Used'].unique()

array([nan, 'STAFFBEV30', 'BRISKIDS5', '83427103-280679704',
       '85193109-287102211', '72015207-238521087', '74501184-247626841',
       'Vera199166324', '85300996-287487213', '85300996-287487214',
       '85010005-286446479', '85313307-287534363', '77042311-256972974',
       '85311769-287527631', '85338787-287620549', '85338787-287620550',
       '85338787-287620551', '85338787-287620552', '85338787-287620553',
       '85338787-287620554', '85338787-287620555', 'DREAM50',
       '180fcb8763', '72983328-241869920', '83050940-279270529',
       '78196229-261265450', '69944748-241082609', '71073165-235331842',
       '83436341-280720932', '77259988-257797134', '76274663-254024976',
       '74533136-247720060', '74416185-247277308', '71837581-237941045',
       '84924661-286149076', '85074675-286673323', '74939751-249184915',
       '74939751-249184918', '74939751-249184916', '74939751-249184917',
       '75805944-252259541', '83782730-282001383', '71405641-236493652',
       '846020

In [67]:
df25['Expiry Date'].unique()

array(['2025-05-29 23:59:00', '2024-06-01 17:40:00',
       '2025-01-01 10:40:00', ..., '2025-07-12 19:50:00',
       '2025-07-12 20:00:00', '2026-05-26 23:59:00'],
      shape=(9061,), dtype=object)

In [68]:
df25['External Payments'].unique()

array([0.])

In [7]:
import pandas as pd
df = pd.read_csv('RR23_UW.csv', nrows=10)
print(df)

           Record Date   Entry Type  Booking ID Booking Location  \
0  2023-01-01 06:00:10  Transaction    57445024  Online checkout   
1  2023-01-01 06:00:10   Adjustment    57445024  Online checkout   
2  2023-01-01 06:00:13  Transaction    57445276  Online checkout   
3  2023-01-01 06:00:13   Adjustment    57445276  Online checkout   
4  2023-01-01 07:15:13  Transaction    58076969  Online checkout   
5  2023-01-01 07:15:13  Transaction    58076969  Online checkout   
6  2023-01-01 07:49:06  Transaction    58077456  Online checkout   
7  2023-01-01 07:49:06  Transaction    58077456  Online checkout   
8  2023-01-01 08:18:44  Transaction    58078032  Online checkout   
9  2023-01-01 08:18:44  Transaction    58078032  Online checkout   

   Payment Device  Product Reporting Name  \
0             NaN                     NaN   
1             NaN                     NaN   
2             NaN                     NaN   
3             NaN                     NaN   
4             NaN         

In [8]:
import pandas as pd
df = pd.read_csv('RR22_UW.csv', nrows=10)
print(df)

           Record Date   Entry Type  Booking ID Booking Location  \
0  2022-05-12 14:02:07  Transaction    51025293  Online checkout   
1  2022-05-30 13:08:40  Transaction    51427003  Online checkout   
2  2022-05-30 13:08:40  Transaction    51427003  Online checkout   
3  2022-05-30 13:08:40  Transaction    51427003  Online checkout   
4  2022-05-30 13:25:28  Transaction    51427415  Online checkout   
5  2022-05-30 13:25:28  Transaction    51427415  Online checkout   
6  2022-05-30 13:26:57  Transaction    51427448  Online checkout   
7  2022-05-30 13:26:57  Transaction    51427448  Online checkout   
8  2022-05-30 13:26:57  Transaction    51427448  Online checkout   
9  2022-05-30 13:26:57  Transaction    51427448  Online checkout   

   Payment Device  Product Reporting Name  \
0             NaN                     NaN   
1             NaN                     NaN   
2             NaN                     NaN   
3             NaN                     NaN   
4             NaN         

In [9]:
import pandas as pd
df = pd.read_csv('RR2401_UW.csv', nrows=10)
print(df)

           Record Date   Entry Type  Booking ID Booking Location  \
0  2024-01-01 03:18:15  Transaction    63392678  Online checkout   
1  2024-01-01 03:18:15   Adjustment    63392678  Online checkout   
2  2024-01-01 03:18:16  Transaction    67815991              POS   
3  2024-01-01 03:18:16   Adjustment    67815991              POS   
4  2024-01-01 05:14:23  Transaction    69989909  Online checkout   
5  2024-01-01 05:14:23  Transaction    69989909  Online checkout   
6  2024-01-01 05:14:23  Transaction    69989909  Online checkout   
7  2024-01-01 05:27:08  Transaction    71103221  Online checkout   
8  2024-01-01 05:27:08  Transaction    71103221  Online checkout   
9  2024-01-01 05:27:08  Transaction    71103221  Online checkout   

   Payment Device  Product Reporting Name  \
0             NaN                     NaN   
1             NaN                     NaN   
2             NaN                     NaN   
3             NaN                     NaN   
4             NaN         

In [10]:
import pandas as pd
df = pd.read_csv('RR2402_UW.csv', nrows=10)
print(df)

           Record Date   Entry Type  Booking ID Booking Location  \
0  2024-07-01 03:18:16  Transaction    67815991              POS   
1  2024-07-01 03:18:16   Adjustment    67815991              POS   
2  2024-07-01 03:27:38  Transaction    78117575  Online checkout   
3  2024-07-01 03:27:38  Transaction    78117575  Online checkout   
4  2024-07-01 05:28:57  Transaction    78117614  Online checkout   
5  2024-07-01 05:37:44  Transaction    78117618  Online checkout   
6  2024-07-01 05:37:44  Transaction    78117618  Online checkout   
7  2024-07-01 05:40:42  Transaction    78117622  Online checkout   
8  2024-07-01 06:24:25  Transaction    78117651  Online checkout   
9  2024-07-01 06:32:24  Transaction    78117659  Online checkout   

   Payment Device  Product Reporting Name  \
0             NaN                     NaN   
1             NaN                     NaN   
2             NaN                     NaN   
3             NaN                     NaN   
4             NaN         

In [11]:
df2401 = pd.read_csv('RR2401_UW.csv')

In [ ]:
df25 = pd.read_csv('RR25_UW.csv')

In [12]:
df2402 = pd.read_csv('RR2402_UW.csv')

/var/folders/_t/s9_cqvqj4_n614936xfgdv_00000gn/T/ipykernel_53477/2116957210.py:1: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df2402 = pd.read_csv('RR2402_UW.csv')


In [13]:
df22 = pd.read_csv('RR22_UW.csv')

/var/folders/_t/s9_cqvqj4_n614936xfgdv_00000gn/T/ipykernel_53477/2640793160.py:1: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df22 = pd.read_csv('RR22_UW.csv')


In [14]:
df23 = pd.read_csv('RR23_UW.csv')

/var/folders/_t/s9_cqvqj4_n614936xfgdv_00000gn/T/ipykernel_53477/3182067635.py:1: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df23 = pd.read_csv('RR23_UW.csv')


In [15]:
dfs = [df22, df23, df2401, df2402, df25]
df = pd.concat(dfs, ignore_index=True)

In [17]:
df.shape

(2880162, 45)

In [18]:
test_df = df.head(100)
print(test_df)

            Record Date   Entry Type  Booking ID Booking Location  \
0   2022-05-12 14:02:07  Transaction    51025293  Online checkout   
1   2022-05-30 13:08:40  Transaction    51427003  Online checkout   
2   2022-05-30 13:08:40  Transaction    51427003  Online checkout   
3   2022-05-30 13:08:40  Transaction    51427003  Online checkout   
4   2022-05-30 13:25:28  Transaction    51427415  Online checkout   
..                  ...          ...         ...              ...   
95  2022-06-05 18:45:43  Transaction    51581409  Online checkout   
96  2022-06-05 18:45:43  Transaction    51581409  Online checkout   
97  2022-06-05 19:33:44  Transaction    51581801  Online checkout   
98  2022-06-05 19:33:44  Transaction    51581801  Online checkout   
99  2022-06-05 19:33:44  Transaction    51581801  Online checkout   

   Payment Device  Product Reporting Name  \
0             NaN                     NaN   
1             NaN                     NaN   
2             NaN                   

In [19]:
print(test_df['Record Date'])

0     2022-05-12 14:02:07
1     2022-05-30 13:08:40
2     2022-05-30 13:08:40
3     2022-05-30 13:08:40
4     2022-05-30 13:25:28
             ...         
95    2022-06-05 18:45:43
96    2022-06-05 18:45:43
97    2022-06-05 19:33:44
98    2022-06-05 19:33:44
99    2022-06-05 19:33:44
Name: Record Date, Length: 100, dtype: object


In [20]:
test_df.to_csv('test_df.csv')

In [28]:
df.dtypes

Record Date                    object
Entry Type                     object
Booking ID                      int64
Booking Location               object
Payment Device                 object
Product Reporting Name        float64
Product Name                   object
Ticket Reporting Name         float64
Ticket Name                    object
Funds Received                float64
Discount                      float64
Fee Revenue                   float64
Tax Collected                 float64
Tax %                         float64
Status                         object
Transaction ID                float64
Transaction Location           object
Payment Method                 object
Gateway ID                     object
GL Code                        object
Ticket Quantity                 int64
Company Name                   object
Tax On Fees                   float64
Deferred Rev                  float64
Other Deferred Rev            float64
Gift Card Def Rev             float64
Acc Receivab

In [62]:
df0 = df.copy()

In [32]:
df1 = df0[['Record Date', 'Funds Received']].copy()

In [33]:
df1.dtypes

Record Date        object
Funds Received    float64
dtype: object

In [34]:
df1['Record Date Converted'] = pd.to_datetime(df1['Record Date'], errors='coerce')

invalid_rows = df1[df1['Record Date Converted'].isna()]

error_indices = invalid_rows.index.tolist()
print("invaild rows：", error_indices)

invaild rows： []


In [35]:
df0['Record Date Converted'] = pd.to_datetime(df0['Record Date'], errors='coerce')

invalid_rows = df0[df0['Record Date Converted'].isna()]

error_indices = invalid_rows.index.tolist()
print("invaild rows：", error_indices)

invaild rows： []


In [36]:
print(df1)

                 Record Date  Funds Received Record Date Converted
0        2022-05-12 14:02:07            1.02   2022-05-12 14:02:07
1        2022-05-30 13:08:40          169.01   2022-05-30 13:08:40
2        2022-05-30 13:08:40           39.63   2022-05-30 13:08:40
3        2022-05-30 13:08:40           19.43   2022-05-30 13:08:40
4        2022-05-30 13:25:28          359.84   2022-05-30 13:25:28
...                      ...             ...                   ...
2880157  2025-07-12 22:43:08            0.00   2025-07-12 22:43:08
2880158  2025-07-12 22:43:08           19.32   2025-07-12 22:43:08
2880159  2025-07-12 22:58:11           31.36   2025-07-12 22:58:11
2880160  2025-07-12 22:58:11            7.32   2025-07-12 22:58:11
2880161  2025-07-12 22:58:11            5.23   2025-07-12 22:58:11

[2880162 rows x 3 columns]


In [37]:
df1.rename(columns={'Record Date Converted': 'date'}, inplace=True)
df1.rename(columns={'Funds Received': 'funds'}, inplace=True)
print(df1.head(10))

           Record Date   funds                date
0  2022-05-12 14:02:07    1.02 2022-05-12 14:02:07
1  2022-05-30 13:08:40  169.01 2022-05-30 13:08:40
2  2022-05-30 13:08:40   39.63 2022-05-30 13:08:40
3  2022-05-30 13:08:40   19.43 2022-05-30 13:08:40
4  2022-05-30 13:25:28  359.84 2022-05-30 13:25:28
5  2022-05-30 13:25:28   16.99 2022-05-30 13:25:28
6  2022-05-30 13:26:57  185.51 2022-05-30 13:26:57
7  2022-05-30 13:26:57  116.00 2022-05-30 13:26:57
8  2022-05-30 13:26:57   11.94 2022-05-30 13:26:57
9  2022-05-30 13:26:57   23.46 2022-05-30 13:26:57


In [39]:
df1['date'] = pd.to_datetime(df1['Record Date']).dt.date
print(df1.head(10))

           Record Date   funds        date
0  2022-05-12 14:02:07    1.02  2022-05-12
1  2022-05-30 13:08:40  169.01  2022-05-30
2  2022-05-30 13:08:40   39.63  2022-05-30
3  2022-05-30 13:08:40   19.43  2022-05-30
4  2022-05-30 13:25:28  359.84  2022-05-30
5  2022-05-30 13:25:28   16.99  2022-05-30
6  2022-05-30 13:26:57  185.51  2022-05-30
7  2022-05-30 13:26:57  116.00  2022-05-30
8  2022-05-30 13:26:57   11.94  2022-05-30
9  2022-05-30 13:26:57   23.46  2022-05-30


In [41]:
df1.drop('Record Date', axis = 1, inplace = True)
print(df1.head(10))

    funds        date
0    1.02  2022-05-12
1  169.01  2022-05-30
2   39.63  2022-05-30
3   19.43  2022-05-30
4  359.84  2022-05-30
5   16.99  2022-05-30
6  185.51  2022-05-30
7  116.00  2022-05-30
8   11.94  2022-05-30
9   23.46  2022-05-30


In [45]:
df_grouped = df1.groupby('date').agg(
    count=('date', 'count'),
    funds=('funds', 'sum')
).reset_index()
print(df_grouped.head(10))

         date  count    funds
0  2022-05-12      1     1.02
1  2022-05-30     32  2741.56
2  2022-06-01      7   452.42
3  2022-06-03     21  2355.81
4  2022-06-04     27  2454.73
5  2022-06-05     16  1494.15
6  2022-06-06     12   590.52
7  2022-06-07     25  1615.69
8  2022-06-08      7   935.53
9  2022-06-09     36  1255.00


In [47]:
df_grouped.shape

(1139, 3)

In [55]:
df_grouped.dtypes

date      object
count      int64
funds    float64
dtype: object

In [49]:
filtered = df_grouped[df_grouped['funds'] < 10000][['date', 'count', 'funds']]
print(filtered)

            date  count    funds
0     2022-05-12      1     1.02
1     2022-05-30     32  2741.56
2     2022-06-01      7   452.42
3     2022-06-03     21  2355.81
4     2022-06-04     27  2454.73
5     2022-06-05     16  1494.15
6     2022-06-06     12   590.52
7     2022-06-07     25  1615.69
8     2022-06-08      7   935.53
9     2022-06-09     36  1255.00
10    2022-06-10      3   240.33
11    2022-06-11      1   409.79
12    2022-06-12     23  1619.74
13    2022-06-13      2   245.81
14    2022-06-14     16   969.10
15    2022-06-15     14  1489.77
16    2022-06-16      9   672.86
17    2022-06-17     17  1273.68
18    2022-06-18    127  1512.58
19    2022-06-19     14  1507.31
20    2022-06-20     32  2868.00
21    2022-06-21     28  2074.64
22    2022-06-22     36  1699.66
23    2022-06-23     14   742.64
24    2022-06-24     19  1958.90
25    2022-06-25     29  2540.78
26    2022-06-26     26  2224.13
27    2022-06-27     12  1021.17
28    2022-06-28     42  2765.37
30    2022

In [57]:
pd.api.types.is_datetime64_any_dtype(df0['Record Date'])

False

In [63]:
df0['date'] = pd.to_datetime(df0['Record Date']).dt.normalize()
print(df0.head(10))

           Record Date   Entry Type  Booking ID Booking Location  \
0  2022-05-12 14:02:07  Transaction    51025293  Online checkout   
1  2022-05-30 13:08:40  Transaction    51427003  Online checkout   
2  2022-05-30 13:08:40  Transaction    51427003  Online checkout   
3  2022-05-30 13:08:40  Transaction    51427003  Online checkout   
4  2022-05-30 13:25:28  Transaction    51427415  Online checkout   
5  2022-05-30 13:25:28  Transaction    51427415  Online checkout   
6  2022-05-30 13:26:57  Transaction    51427448  Online checkout   
7  2022-05-30 13:26:57  Transaction    51427448  Online checkout   
8  2022-05-30 13:26:57  Transaction    51427448  Online checkout   
9  2022-05-30 13:26:57  Transaction    51427448  Online checkout   

  Payment Device  Product Reporting Name  \
0            NaN                     NaN   
1            NaN                     NaN   
2            NaN                     NaN   
3            NaN                     NaN   
4            NaN               

In [66]:
df0.dtypes

Entry Type                            object
Booking ID                             int64
Booking Location                      object
Payment Device                        object
Product Reporting Name               float64
Product Name                          object
Ticket Reporting Name                float64
Ticket Name                           object
Funds Received                       float64
Discount                             float64
Fee Revenue                          float64
Tax Collected                        float64
Tax %                                float64
Status                                object
Transaction ID                       float64
Transaction Location                  object
Payment Method                        object
Gateway ID                            object
GL Code                               object
Ticket Quantity                        int64
Company Name                          object
Tax On Fees                          float64
Deferred R

In [67]:
pd.api.types.is_datetime64_any_dtype(df0['date'])

True

In [73]:
df0 = df0[df0['date'] > '2022-07-01']

In [74]:
df0.head(10)

Entry Type  Booking ID Booking Location Payment Device  \
1281  Transaction    52303331  Online checkout            NaN   
1282  Transaction    52303331  Online checkout            NaN   
1283  Transaction    52303707  Online checkout            NaN   
1284  Transaction    52303707  Online checkout            NaN   
1285  Transaction    52303707  Online checkout            NaN   
1286  Transaction    52303707  Online checkout            NaN   
1287  Transaction    52303707  Online checkout            NaN   
1288  Transaction    52303707  Online checkout            NaN   
1289  Transaction    52304252  Online checkout            NaN   
1290  Transaction    52304976  Online checkout            NaN   

      Product Reporting Name  \
1281                     NaN   
1282                     NaN   
1283                     NaN   
1284                     NaN   
1285                     NaN   
1286                     NaN   
1287                     NaN   
1288                     NaN   
1289                     NaN   
1290                     NaN   

                                           Product Name  \
1281                 Astro Tots Adventure Playland Pass   
1282  2 hr 3-5yrs Junior Gizmo and Launchpad Pass (W...   
1283  2 hr 3-5yrs Junior Gizmo and Launchpad Pass (W...   
1284                 Astro Tots Adventure Playland Pass   
1285     2 hr 6yrs+ The Universe Pass (Public Holidays)   
1286           Multiverse Mega Slide (Age 6+) - 3 Rides   
1287                                         GRIP SOCKS   
1288                                     Animal Ride On   
1289  2 hr 3-5yrs Junior Gizmo and Launchpad Pass (W...   
1290  VIP Infinity 6Yrs+ Unlimited Pass (Weekends & ...   

      Ticket Reporting Name  \
1281                    NaN   
1282                    NaN   
1283                    NaN   
1284                    NaN   
1285                    NaN   
1286                    NaN   
1287                    NaN   
1288                    NaN   
1289                    NaN   
1290                    NaN   

                                            Ticket Name  Funds Received  \
1281                    Astro Tots 2 hrs Adventure Pass           15.66   
1282  2 hr 3-5yrs Gizmo's Galaxy and Launchpad Pass ...           31.32   
1283  2 hr 3-5yrs Gizmo's Galaxy and Launchpad Pass ...           64.24   
1284                    Astro Tots 2 hrs Adventure Pass           32.12   
1285  2 hr 6yrs+ The Universe Pass (Weekends & Holid...           85.65   
1286           Multiverse Mega Slide (Age 6+) - 3 Rides           12.85   
1287                                      Area 51 Socks           14.99   
1288                                     Animal Ride On           25.70   
1289  2 hr 3-5yrs Gizmo's Galaxy and Launchpad Pass ...           31.65   
1290  VIP Infinity 6Yrs+ Unlimited Pass (Weekends & ...           72.49   

      Discount  ...  Expired Ticket Quantity  Recognised Ticket Quantity  \
1281       0.0  ...                        0                           0   
1282       0.0  ...                        0                           0   
1283       0.0  ...                        0                           0   
1284       0.0  ...                        0                           0   
1285       0.0  ...                        0                           0   
1286       0.0  ...                        0                           0   
1287       0.0  ...                        0                           0   
1288       0.0  ...                        0                           0   
1289       0.0  ...                        0                           0   
1290       0.0  ...                        0                           0   

      Credit Card Fee Amount Transaction Fee Amount  \
1281                     0.0                    0.0   
1282                     0.0                    0.0   
1283                     0.0                    0.0   
1284                     0.0                    0.0   
1285    

In [75]:
df0['Ticket Name'].nunique()

1749

In [72]:
df_grouped.head(10)

date  count    funds
0  2022-05-12      1     1.02
1  2022-05-30     32  2741.56
2  2022-06-01      7   452.42
3  2022-06-03     21  2355.81
4  2022-06-04     27  2454.73
5  2022-06-05     16  1494.15
6  2022-06-06     12   590.52
7  2022-06-07     25  1615.69
8  2022-06-08      7   935.53
9  2022-06-09     36  1255.00

In [76]:
pd.api.types.is_datetime64_any_dtype(df_grouped['date'])

False

In [77]:
df_grouped['date'] = pd.to_datetime(df_grouped['date']).dt.normalize()
pd.api.types.is_datetime64_any_dtype(df_grouped['date'])

True

In [78]:
df_grouped = df_grouped[df_grouped['date'] > '2022-07-01']

In [83]:
df_grouped = df_grouped[df_grouped['date'] > '2022-07-03']
df_grouped.reset_index(drop=True, inplace=True)
df_grouped.head(10)

date  count     funds
0 2022-07-04   1004  25294.82
1 2022-07-05   1647  35762.88
2 2022-07-06   2418  38736.68
3 2022-07-07    727  34504.45
4 2022-07-08   4417  52519.30
5 2022-07-09   3028  25652.15
6 2022-07-10   2303  25455.29
7 2022-07-11   1288  22235.53
8 2022-07-12    940  16772.46
9 2022-07-13    380  12114.32

In [92]:
import holidays

years = df_grouped['date'].dt.year.unique().tolist()
qld_holidays = holidays.Australia(subdiv='QLD', years=years)
df_grouped['is_holiday'] = df_grouped['date'].dt.date.isin(qld_holidays)
df_grouped['is_holiday'] = df_grouped['is_holiday'].astype(int)
df_grouped.head(10)

date  count     funds  is_holiday  weekday
0 2022-07-04   1004  25294.82           0        0
1 2022-07-05   1647  35762.88           0        1
2 2022-07-06   2418  38736.68           0        2
3 2022-07-07    727  34504.45           0        3
4 2022-07-08   4417  52519.30           0        4
5 2022-07-09   3028  25652.15           0        5
6 2022-07-10   2303  25455.29           0        6
7 2022-07-11   1288  22235.53           0        0
8 2022-07-12    940  16772.46           0        1
9 2022-07-13    380  12114.32           0        2

In [96]:
df_grouped[df_grouped['is_holiday'] == 1].shape

(39, 5)

In [88]:
df_grouped['date'] = pd.to_datetime(df_grouped['date'])
df_grouped['weekday'] = df_grouped['date'].dt.weekday

In [89]:
df_grouped.head(10)

date  count     funds  is_holiday  weekday
0 2022-07-04   1004  25294.82           0        0
1 2022-07-05   1647  35762.88           0        1
2 2022-07-06   2418  38736.68           0        2
3 2022-07-07    727  34504.45           0        3
4 2022-07-08   4417  52519.30           0        4
5 2022-07-09   3028  25652.15           0        5
6 2022-07-10   2303  25455.29           0        6
7 2022-07-11   1288  22235.53           0        0
8 2022-07-12    940  16772.46           0        1
9 2022-07-13    380  12114.32           0        2

In [98]:
school_holiday_ranges = [
    # 2022
    ('2022-06-25', '2022-07-10'),
    ('2022-09-17', '2022-10-03'),
    ('2022-12-10', '2023-01-22'),
    # 2023
    ('2023-04-01', '2023-04-16'),
    ('2023-06-24', '2023-07-09'),
    ('2023-09-16', '2023-10-02'),
    ('2023-12-09', '2024-01-21'),
    # 2024
    ('2024-03-29', '2024-04-14'),
    ('2024-06-22', '2024-07-07'),
    ('2024-09-14', '2024-09-29'),
    ('2024-12-14', '2025-01-27'),
    # 2025
    ('2025-04-05', '2025-04-21'),
    ('2025-06-28', '2025-07-13'),
]

holiday_dates = set()
for start, end in school_holiday_ranges:
    dates = pd.date_range(start=start, end=end)
    holiday_dates.update(dates)

df_grouped['is_school_holiday'] = df_grouped['date'].isin(holiday_dates).astype(int)
df_grouped[:-1]

date  count     funds  is_holiday  weekday  is_school_holiday
0    2022-07-04   1004  25294.82           0        0                  1
1    2022-07-05   1647  35762.88           0        1                  1
2    2022-07-06   2418  38736.68           0        2                  1
3    2022-07-07    727  34504.45           0        3                  1
4    2022-07-08   4417  52519.30           0        4                  1
...         ...    ...       ...         ...      ...                ...
1099 2025-07-07   4647  56965.01           0        0                  1
1100 2025-07-08   4609  54898.69           0        1                  1
1101 2025-07-09   5479  49112.31           0        2                  1
1102 2025-07-10   5155  48656.56           0        3                  1
1103 2025-07-11   6106  51875.73           0        4                  1

[1104 rows x 6 columns]

In [99]:
df_maxtemp = pd.read_csv('weather/UD/max_temp.csv')
df_maxtemp.head(10)

Product code  Bureau of Meteorology station number  Year  Month  Day  \
0   IDCJAC0010                                 40211  1939      1    1   
1   IDCJAC0010                                 40211  1939      1    2   
2   IDCJAC0010                                 40211  1939      1    3   
3   IDCJAC0010                                 40211  1939      1    4   
4   IDCJAC0010                                 40211  1939      1    5   
5   IDCJAC0010                                 40211  1939      1    6   
6   IDCJAC0010                                 40211  1939      1    7   
7   IDCJAC0010                                 40211  1939      1    8   
8   IDCJAC0010                                 40211  1939      1    9   
9   IDCJAC0010                                 40211  1939      1   10   

   Maximum temperature (Degree C)  \
0                             NaN   
1                             NaN   
2                             NaN   
3                             NaN   
4                             NaN   
5                             NaN   
6                             NaN   
7                             NaN   
8                             NaN   
9                             NaN   

   Days of accumulation of maximum temperature Quality  
0                                          NaN     NaN  
1                                          NaN     NaN  
2                                          NaN     NaN  
3                                          NaN     NaN  
4                                          NaN     NaN  
5                                          NaN     NaN  
6                                          NaN     NaN  
7                                          NaN     NaN  
8                                          NaN     NaN  
9                                          NaN     NaN

In [101]:
df_maxtemp.shape

(31616, 8)

In [102]:
df_maxtemp['date'] = pd.to_datetime(df_maxtemp[['Year', 'Month', 'Day']])

df_maxtemp.rename(columns={
    'Maximum temperature (Degree C)': 'max_temp'
}, inplace=True)
df_maxtemp.head(10)

Product code  Bureau of Meteorology station number  Year  Month  Day  \
0   IDCJAC0010                                 40211  1939      1    1   
1   IDCJAC0010                                 40211  1939      1    2   
2   IDCJAC0010                                 40211  1939      1    3   
3   IDCJAC0010                                 40211  1939      1    4   
4   IDCJAC0010                                 40211  1939      1    5   
5   IDCJAC0010                                 40211  1939      1    6   
6   IDCJAC0010                                 40211  1939      1    7   
7   IDCJAC0010                                 40211  1939      1    8   
8   IDCJAC0010                                 40211  1939      1    9   
9   IDCJAC0010                                 40211  1939      1   10   

   max_temp  Days of accumulation of maximum temperature Quality       date  
0       NaN                                          NaN     NaN 1939-01-01  
1       NaN                                          NaN     NaN 1939-01-02  
2       NaN                                          NaN     NaN 1939-01-03  
3       NaN                                          NaN     NaN 1939-01-04  
4       NaN                                          NaN     NaN 1939-01-05  
5       NaN                                          NaN     NaN 1939-01-06  
6       NaN                                          NaN     NaN 1939-01-07  
7       NaN                                          NaN     NaN 1939-01-08  
8       NaN                                          NaN     NaN 1939-01-09  
9       NaN                                          NaN     NaN 1939-01-10

In [103]:
pd.api.types.is_datetime64_any_dtype(df_maxtemp['date'])

True

In [108]:
df_maxtemp.head(10)

Product code  Bureau of Meteorology station number  max_temp  \
0   IDCJAC0010                                 40211       NaN   
1   IDCJAC0010                                 40211       NaN   
2   IDCJAC0010                                 40211       NaN   
3   IDCJAC0010                                 40211       NaN   
4   IDCJAC0010                                 40211       NaN   
5   IDCJAC0010                                 40211       NaN   
6   IDCJAC0010                                 40211       NaN   
7   IDCJAC0010                                 40211       NaN   
8   IDCJAC0010                                 40211       NaN   
9   IDCJAC0010                                 40211       NaN   

   Days of accumulation of maximum temperature Quality       date  
0                                          NaN     NaN 1939-01-01  
1                                          NaN     NaN 1939-01-02  
2                                          NaN     NaN 1939-01-03  
3                                          NaN     NaN 1939-01-04  
4                                          NaN     NaN 1939-01-05  
5                                          NaN     NaN 1939-01-06  
6                                          NaN     NaN 1939-01-07  
7                                          NaN     NaN 1939-01-08  
8                                          NaN     NaN 1939-01-09  
9                                          NaN     NaN 1939-01-10

In [109]:
df_maxtemp.drop('Days of accumulation of maximum temperature', axis = 1, inplace = True)
df_maxtemp.drop('Quality', axis = 1, inplace = True)
df_maxtemp.head(10)

Product code  Bureau of Meteorology station number  max_temp       date
0   IDCJAC0010                                 40211       NaN 1939-01-01
1   IDCJAC0010                                 40211       NaN 1939-01-02
2   IDCJAC0010                                 40211       NaN 1939-01-03
3   IDCJAC0010                                 40211       NaN 1939-01-04
4   IDCJAC0010                                 40211       NaN 1939-01-05
5   IDCJAC0010                                 40211       NaN 1939-01-06
6   IDCJAC0010                                 40211       NaN 1939-01-07
7   IDCJAC0010                                 40211       NaN 1939-01-08
8   IDCJAC0010                                 40211       NaN 1939-01-09
9   IDCJAC0010                                 40211       NaN 1939-01-10

In [110]:
df_maxtemp.drop('Bureau of Meteorology station number', axis = 1, inplace = True)
df_maxtemp.drop('Product code', axis = 1, inplace = True)
df_maxtemp.head(10)

max_temp       date
0       NaN 1939-01-01
1       NaN 1939-01-02
2       NaN 1939-01-03
3       NaN 1939-01-04
4       NaN 1939-01-05
5       NaN 1939-01-06
6       NaN 1939-01-07
7       NaN 1939-01-08
8       NaN 1939-01-09
9       NaN 1939-01-10

In [111]:
df_merged1 = pd.merge(df_grouped, df_maxtemp, on='date', how='left')
df_merged1.head(10)

date  count     funds  is_holiday  weekday  is_school_holiday  \
0 2022-07-04   1004  25294.82           0        0                  1   
1 2022-07-05   1647  35762.88           0        1                  1   
2 2022-07-06   2418  38736.68           0        2                  1   
3 2022-07-07    727  34504.45           0        3                  1   
4 2022-07-08   4417  52519.30           0        4                  1   
5 2022-07-09   3028  25652.15           0        5                  1   
6 2022-07-10   2303  25455.29           0        6                  1   
7 2022-07-11   1288  22235.53           0        0                  0   
8 2022-07-12    940  16772.46           0        1                  0   
9 2022-07-13    380  12114.32           0        2                  0   

   max_temp  
0      14.0  
1      13.5  
2      19.0  
3       NaN  
4      19.2  
5      18.8  
6      20.5  
7      20.2  
8      19.6  
9      19.3

In [113]:
print(df_merged1.isna().sum())

date                 0
count                0
funds                0
is_holiday           0
weekday              0
is_school_holiday    0
max_temp             4
dtype: int64


In [115]:
import numpy as np

temps = df_merged1['max_temp'].values.copy()

for i in range(1, len(temps) - 1):
    if np.isnan(temps[i]) and not np.isnan(temps[i - 1]) and not np.isnan(temps[i + 1]):
        temps[i] = (temps[i - 1] + temps[i + 1]) / 2
        
df_merged1['max_temp'] = temps
print(df_merged1.isna().sum())

date                 0
count                0
funds                0
is_holiday           0
weekday              0
is_school_holiday    0
max_temp             0
dtype: int64


In [118]:
df_mintemp = pd.read_csv('weather/UD/min_temp.csv')
df_mintemp['date'] = pd.to_datetime(df_mintemp[['Year', 'Month', 'Day']])

df_mintemp.rename(columns={
    'Minimum temperature (Degree C)': 'min_temp'
}, inplace=True)
df_mintemp.head(10)

Product code  Bureau of Meteorology station number  Year  Month  Day  \
0   IDCJAC0011                                 40211  1939      1    1   
1   IDCJAC0011                                 40211  1939      1    2   
2   IDCJAC0011                                 40211  1939      1    3   
3   IDCJAC0011                                 40211  1939      1    4   
4   IDCJAC0011                                 40211  1939      1    5   
5   IDCJAC0011                                 40211  1939      1    6   
6   IDCJAC0011                                 40211  1939      1    7   
7   IDCJAC0011                                 40211  1939      1    8   
8   IDCJAC0011                                 40211  1939      1    9   
9   IDCJAC0011                                 40211  1939      1   10   

   min_temp  Days of accumulation of minimum temperature Quality       date  
0       NaN                                          NaN     NaN 1939-01-01  
1       NaN                                          NaN     NaN 1939-01-02  
2       NaN                                          NaN     NaN 1939-01-03  
3       NaN                                          NaN     NaN 1939-01-04  
4       NaN                                          NaN     NaN 1939-01-05  
5       NaN                                          NaN     NaN 1939-01-06  
6       NaN                                          NaN     NaN 1939-01-07  
7       NaN                                          NaN     NaN 1939-01-08  
8       NaN                                          NaN     NaN 1939-01-09  
9       NaN                                          NaN     NaN 1939-01-10

In [119]:
df_mintemp.drop('Product code', axis = 1, inplace = True)
df_mintemp.drop('Bureau of Meteorology station number', axis = 1, inplace = True)
df_mintemp.drop('Year', axis = 1, inplace = True)
df_mintemp.drop('Month', axis = 1, inplace = True)
df_mintemp.drop('Day', axis = 1, inplace = True)
df_mintemp.drop('Days of accumulation of minimum temperature', axis = 1, inplace = True)
df_mintemp.drop('Quality', axis = 1, inplace = True)
df_mintemp.head(10)

min_temp       date
0       NaN 1939-01-01
1       NaN 1939-01-02
2       NaN 1939-01-03
3       NaN 1939-01-04
4       NaN 1939-01-05
5       NaN 1939-01-06
6       NaN 1939-01-07
7       NaN 1939-01-08
8       NaN 1939-01-09
9       NaN 1939-01-10

In [120]:
df_merged2 = pd.merge(df_merged1, df_mintemp, on='date', how='left')
temps = df_merged2['min_temp'].values.copy()

for i in range(1, len(temps) - 1):
    if np.isnan(temps[i]) and not np.isnan(temps[i - 1]) and not np.isnan(temps[i + 1]):
        temps[i] = (temps[i - 1] + temps[i + 1]) / 2
        
df_merged2['min_temp'] = temps
print(df_merged2.isna().sum())

date                 0
count                0
funds                0
is_holiday           0
weekday              0
is_school_holiday    0
max_temp             0
min_temp             0
dtype: int64


In [121]:
df_merged2.head(10)

date  count     funds  is_holiday  weekday  is_school_holiday  \
0 2022-07-04   1004  25294.82           0        0                  1   
1 2022-07-05   1647  35762.88           0        1                  1   
2 2022-07-06   2418  38736.68           0        2                  1   
3 2022-07-07    727  34504.45           0        3                  1   
4 2022-07-08   4417  52519.30           0        4                  1   
5 2022-07-09   3028  25652.15           0        5                  1   
6 2022-07-10   2303  25455.29           0        6                  1   
7 2022-07-11   1288  22235.53           0        0                  0   
8 2022-07-12    940  16772.46           0        1                  0   
9 2022-07-13    380  12114.32           0        2                  0   

   max_temp  min_temp  
0      14.0      11.4  
1      13.5      10.1  
2      19.0      10.9  
3      19.1      11.9  
4      19.2       9.6  
5      18.8       7.0  
6      20.5       5.2  
7      20.2       4.2  
8      19.6       5.8  
9      19.3       7.6

In [122]:
df_rainfall = pd.read_csv('weather/UD/rainfall.csv')
df_rainfall.head(10)

Product code  Bureau of Meteorology station number  Year  Month  Day  \
0   IDCJAC0009                                 40784  2000      1    1   
1   IDCJAC0009                                 40784  2000      1    2   
2   IDCJAC0009                                 40784  2000      1    3   
3   IDCJAC0009                                 40784  2000      1    4   
4   IDCJAC0009                                 40784  2000      1    5   
5   IDCJAC0009                                 40784  2000      1    6   
6   IDCJAC0009                                 40784  2000      1    7   
7   IDCJAC0009                                 40784  2000      1    8   
8   IDCJAC0009                                 40784  2000      1    9   
9   IDCJAC0009                                 40784  2000      1   10   

   Rainfall amount (millimetres)  \
0                            NaN   
1                            NaN   
2                            NaN   
3                            NaN   
4                            NaN   
5                            NaN   
6                            NaN   
7                            NaN   
8                            NaN   
9                            NaN   

   Period over which rainfall was measured (days) Quality  
0                                             NaN     NaN  
1                                             NaN     NaN  
2                                             NaN     NaN  
3                                             NaN     NaN  
4                                             NaN     NaN  
5                                             NaN     NaN  
6                                             NaN     NaN  
7                                             NaN     NaN  
8                                             NaN     NaN  
9                                             NaN     NaN

In [123]:
df_rainfall['date'] = pd.to_datetime(df_rainfall[['Year', 'Month', 'Day']])

df_rainfall.rename(columns={
    'Rainfall amount (millimetres)': 'rainfall'
}, inplace=True)
df_rainfall.drop('Product code', axis = 1, inplace = True)
df_rainfall.drop('Bureau of Meteorology station number', axis = 1, inplace = True)
df_rainfall.drop('Year', axis = 1, inplace = True)
df_rainfall.drop('Month', axis = 1, inplace = True)
df_rainfall.drop('Day', axis = 1, inplace = True)
df_rainfall.drop('Period over which rainfall was measured (days)', axis = 1, inplace = True)
df_rainfall.drop('Quality', axis = 1, inplace = True)
df_rainfall.head(10)

rainfall       date
0       NaN 2000-01-01
1       NaN 2000-01-02
2       NaN 2000-01-03
3       NaN 2000-01-04
4       NaN 2000-01-05
5       NaN 2000-01-06
6       NaN 2000-01-07
7       NaN 2000-01-08
8       NaN 2000-01-09
9       NaN 2000-01-10

In [125]:
df_merged3 = pd.merge(df_merged2, df_rainfall, on='date', how='left')
temps = df_merged3['rainfall'].values.copy()

for i in range(1, len(temps) - 1):
    if np.isnan(temps[i]) and not np.isnan(temps[i - 1]) and not np.isnan(temps[i + 1]):
        print(i)
        temps[i] = (temps[i - 1] + temps[i + 1]) / 2
        
df_merged3['rainfall'] = temps
print(df_merged3.isna().sum())

date                  0
count                 0
funds                 0
is_holiday            0
weekday               0
is_school_holiday     0
max_temp              0
min_temp              0
rainfall             98
dtype: int64


In [127]:
df_merged3[df_merged3['rainfall'].isna()]

date  count     funds  is_holiday  weekday  is_school_holiday  \
799  2024-09-10   1395  25813.00           0        1                  0   
800  2024-09-11   1526  20500.45           0        2                  0   
801  2024-09-12   1537  21553.46           0        3                  0   
802  2024-09-13   2735  31261.17           0        4                  0   
803  2024-09-14   6545  38529.39           0        5                  1   
...         ...    ...       ...         ...      ...                ...   
1076 2025-06-14   5694  34159.70           0        5                  0   
1077 2025-06-15   4876  28239.51           0        6                  0   
1078 2025-06-16   1247  17859.15           0        0                  0   
1079 2025-06-17   1010  18668.82           0        1                  0   
1080 2025-06-18   1108  16337.50           0        2                  0   

      max_temp  min_temp  rainfall  
799       26.7      17.8       NaN  
800       26.7      15.8       NaN  
801       28.0      13.5       NaN  
802       23.2      12.3       NaN  
803       23.8      10.8       NaN  
...        ...       ...       ...  
1076      20.7       4.9       NaN  
1077      22.2       5.9       NaN  
1078      23.0       6.2       NaN  
1079      18.0       9.4       NaN  
1080      21.5      11.3       NaN  

[98 rows x 9 columns]

In [128]:
df_rainfall2 = pd.read_csv('weather/UD/rainfall2.csv')
df_rainfall2.head(10)

Product code  Bureau of Meteorology station number  Year  Month  Day  \
0   IDCJAC0009                                 40715  1980      1    1   
1   IDCJAC0009                                 40715  1980      1    2   
2   IDCJAC0009                                 40715  1980      1    3   
3   IDCJAC0009                                 40715  1980      1    4   
4   IDCJAC0009                                 40715  1980      1    5   
5   IDCJAC0009                                 40715  1980      1    6   
6   IDCJAC0009                                 40715  1980      1    7   
7   IDCJAC0009                                 40715  1980      1    8   
8   IDCJAC0009                                 40715  1980      1    9   
9   IDCJAC0009                                 40715  1980      1   10   

   Rainfall amount (millimetres)  \
0                            NaN   
1                            NaN   
2                            NaN   
3                            NaN   
4                            NaN   
5                            NaN   
6                            NaN   
7                            NaN   
8                            NaN   
9                            NaN   

   Period over which rainfall was measured (days) Quality  
0                                             NaN     NaN  
1                                             NaN     NaN  
2                                             NaN     NaN  
3                                             NaN     NaN  
4                                             NaN     NaN  
5                                             NaN     NaN  
6                                             NaN     NaN  
7                                             NaN     NaN  
8                                             NaN     NaN  
9                                             NaN     NaN

In [129]:
df_rainfall2['date'] = pd.to_datetime(df_rainfall2[['Year', 'Month', 'Day']])

df_rainfall2.rename(columns={
    'Rainfall amount (millimetres)': 'rainfall'
}, inplace=True)
df_rainfall2.drop('Product code', axis = 1, inplace = True)
df_rainfall2.drop('Bureau of Meteorology station number', axis = 1, inplace = True)
df_rainfall2.drop('Year', axis = 1, inplace = True)
df_rainfall2.drop('Month', axis = 1, inplace = True)
df_rainfall2.drop('Day', axis = 1, inplace = True)
df_rainfall2.drop('Period over which rainfall was measured (days)', axis = 1, inplace = True)
df_rainfall2.drop('Quality', axis = 1, inplace = True)
df_rainfall2.head(10)

rainfall       date
0       NaN 1980-01-01
1       NaN 1980-01-02
2       NaN 1980-01-03
3       NaN 1980-01-04
4       NaN 1980-01-05
5       NaN 1980-01-06
6       NaN 1980-01-07
7       NaN 1980-01-08
8       NaN 1980-01-09
9       NaN 1980-01-10

In [130]:
df_rainfall2 = df_rainfall2.rename(columns={'rainfall': 'rainfall_new'})
df_merged3 = df_merged3.merge(df_rainfall2[['date', 'rainfall_new']], on='date', how='left')
df_merged3['rainfall'] = df_merged3['rainfall'].fillna(df_merged3['rainfall_new'])
df_merged3.drop(columns=['rainfall_new'], inplace=True)
df_merged3[df_merged3['rainfall'].isna()]

Empty DataFrame
Columns: [date, count, funds, is_holiday, weekday, is_school_holiday, max_temp, min_temp, rainfall]
Index: []

In [132]:
df_solar = pd.read_csv('weather/UD/solar.csv')
df_solar.head(10)

Product code  Bureau of Meteorology station number  Year  Month  Day  \
0   IDCJAC0016                                 40974  1990      1    1   
1   IDCJAC0016                                 40974  1990      1    2   
2   IDCJAC0016                                 40974  1990      1    3   
3   IDCJAC0016                                 40974  1990      1    4   
4   IDCJAC0016                                 40974  1990      1    5   
5   IDCJAC0016                                 40974  1990      1    6   
6   IDCJAC0016                                 40974  1990      1    7   
7   IDCJAC0016                                 40974  1990      1    8   
8   IDCJAC0016                                 40974  1990      1    9   
9   IDCJAC0016                                 40974  1990      1   10   

   Daily global solar exposure (MJ/m*m)  
0                                  32.8  
1                                  33.6  
2                                   NaN  
3                                  33.2  
4                                  18.9  
5                                  15.8  
6                                  22.5  
7                                  16.6  
8                                  10.7  
9                                  21.2

In [133]:
df_solar['date'] = pd.to_datetime(df_solar[['Year', 'Month', 'Day']])

df_solar.rename(columns={
    'Daily global solar exposure (MJ/m*m)': 'solar'
}, inplace=True)
df_solar.drop('Product code', axis = 1, inplace = True)
df_solar.drop('Bureau of Meteorology station number', axis = 1, inplace = True)
df_solar.drop('Year', axis = 1, inplace = True)
df_solar.drop('Month', axis = 1, inplace = True)
df_solar.drop('Day', axis = 1, inplace = True)
df_solar.head(10)

solar       date
0   32.8 1990-01-01
1   33.6 1990-01-02
2    NaN 1990-01-03
3   33.2 1990-01-04
4   18.9 1990-01-05
5   15.8 1990-01-06
6   22.5 1990-01-07
7   16.6 1990-01-08
8   10.7 1990-01-09
9   21.2 1990-01-10

In [135]:
df_merged4 = pd.merge(df_merged3, df_solar, on='date', how='left')
temps = df_merged4['solar'].values.copy()

for i in range(1, len(temps) - 1):
    if np.isnan(temps[i]) and not np.isnan(temps[i - 1]) and not np.isnan(temps[i + 1]):
        print(i)
        temps[i] = (temps[i - 1] + temps[i + 1]) / 2
        
df_merged4['solar'] = temps
print(df_merged4.isna().sum())

131
880
date                 0
count                0
funds                0
is_holiday           0
weekday              0
is_school_holiday    0
max_temp             0
min_temp             0
rainfall             0
solar                0
dtype: int64


In [136]:
df_merged4.head(10)

date  count     funds  is_holiday  weekday  is_school_holiday  \
0 2022-07-04   1004  25294.82           0        0                  1   
1 2022-07-05   1647  35762.88           0        1                  1   
2 2022-07-06   2418  38736.68           0        2                  1   
3 2022-07-07    727  34504.45           0        3                  1   
4 2022-07-08   4417  52519.30           0        4                  1   
5 2022-07-09   3028  25652.15           0        5                  1   
6 2022-07-10   2303  25455.29           0        6                  1   
7 2022-07-11   1288  22235.53           0        0                  0   
8 2022-07-12    940  16772.46           0        1                  0   
9 2022-07-13    380  12114.32           0        2                  0   

   max_temp  min_temp  rainfall  solar  
0      14.0      11.4       0.0    5.0  
1      13.5      10.1      12.0    4.7  
2      19.0      10.9      10.0   10.9  
3      19.1      11.9       0.0   14.1  
4      19.2       9.6       0.0   14.2  
5      18.8       7.0       0.0   14.2  
6      20.5       5.2       0.0   12.7  
7      20.2       4.2       0.0   11.0  
8      19.6       5.8       0.0   10.6  
9      19.3       7.6       4.0   13.8

In [137]:
df.columns

Index(['Record Date', 'Entry Type', 'Booking ID', 'Booking Location',
       'Payment Device', 'Product Reporting Name', 'Product Name',
       'Ticket Reporting Name', 'Ticket Name', 'Funds Received', 'Discount',
       'Fee Revenue', 'Tax Collected', 'Tax %', 'Status', 'Transaction ID',
       'Transaction Location', 'Payment Method', 'Gateway ID', 'GL Code',
       'Ticket Quantity', 'Company Name', 'Tax On Fees', 'Deferred Rev',
       'Other Deferred Rev', 'Gift Card Def Rev', 'Acc Receivable',
       'Gross Revenue', 'Discounts Recognised', 'Tax Payable', 'Net Revenue',
       'Unit Cost', 'Product Id', 'Item Transaction Value', 'Item Quantity',
       'Redeemed Ticket Quantity', 'Expired Ticket Quantity',
       'Recognised Ticket Quantity', 'Credit Card Fee Amount',
       'Transaction Fee Amount', 'Product Booking Fee Amount',
       'Booking Modifier Amount', 'Discount Code Used', 'Expiry Date',
       'External Payments'],
      dtype='object')

In [139]:
df['Product Name'].nunique()

626

In [140]:
df['Ticket Name'].nunique()

1752

In [142]:
product_counts = df['Product Name'].value_counts().reset_index()
product_counts.columns = ['Product Name', 'Count']

product_counts.to_csv('unique_product_names.csv', index=False)

ticket_counts = df['Ticket Name'].value_counts().reset_index()
ticket_counts.columns = ['Ticket Name', 'Count']

ticket_counts.to_csv('unique_ticket_names.csv', index=False)